bank_app/urls.py
from django.urls import path
from . import views

app_name = 'bank_app'

urlpatterns = [
    path('home', views.index, name='index'),
    path('customer', views.index, name='customer'),
    path('employee', views.index, name='employee'),
    path('get_customers_partial', views.get_customers_partial, name='get_customers_partial'),
    path('create_customer', views.create_customer, name='create_customer'),
    path('customer_details/<int:pk>', views.customer_details, name='customer_details'),
    path('create_account', views.create_account, name='create_account'),
    path('get_accounts_partial/<int:pk>', views.get_accounts_partial, name='get_accounts_partial'),
    path('set_rank', views.set_rank, name='set_rank'),
    path('create_transfer', views.create_transfer, name='create_transfer'),
    path('create_loan', views.create_loan, name='create_loan'),
    path('account_details/<uuid:pk>', views.account_details, name='account_details'),
    path('get_account_movements_partial/<uuid:pk>', views.get_account_movements_partial, name='get_account_movements_partial'),
    path('logout', views.logout, name='logout'),
    path('test_me', views.test_me, name="test_me"),
    path('api/external_transfer', views.external_transfer, name="external_transfer"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from two_factor.views import LoginView, SetupView
from two_factor.urls import urlpatterns as tf_urls
from bank_app.apis import LedgerViewSet

# REST API
from rest_framework import routers
router = routers.DefaultRouter()
router.register(r'ledgers', LedgerViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bank/', include('bank_app.urls')),
    # 2FA
    path('', include(tf_urls)),
    path('', LoginView.as_view(), name='login'),
    path('setup/', SetupView.as_view(), name='setup'),
    # REST API
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

bank_app/models.py
from django.db import models, transaction
from django.contrib.auth.models import User
from django.conf import settings
import uuid
from decimal import Decimal
import requests
import json


class Customer(models.Model):
    user = models.OneToOneField(User, primary_key=True, on_delete=models.PROTECT)
    RANKS = (
        ("basic", "Basic"),
        ("silver", "Silver"),
        ("gold", "Gold"),
    )
    rank = models.CharField(max_length=300, choices=RANKS, default="Basic")
    phone = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.pk} - {self.user} - {self.rank} - {self.phone}"

    @classmethod
    def create(cls, username, first_name, last_name, phone, email, password):
        user = User.objects.create_user(
            username=username,
            first_name=first_name,
            last_name=last_name,
            email=email,
            password=password
        )
        customer = Customer()
        customer.phone = phone
        customer.user = user
        customer.save()
        return customer

    @classmethod
    def set_rank(self, rank):
        if (any(rank in i for i in self.RANKS)):
            self.objects.update(rank=rank)

    @classmethod
    def create_loan(self, name, pk, amount, to_account_id):
        with transaction.atomic():
            # Create a loan account
            account = Account.create(name=name, pk=pk, is_loan=True)

            # Make transfer = - on loan account, + on chosen account
            from_text = f"Loan: {name}"
            to_text = f"Loan: {name}"
            from_account_id = account.pk
            Ledger.internal_transfer(amount, from_account_id, to_account_id, from_text, to_text, is_loan=True)
        return account

    @property
    def can_make_loan(self):
        if self.rank == "Basic":
            return False
        else:
            return True

    @property
    def accounts(self):
        return Account.objects.filter(user=self.user)


class Employee(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.pk} - {self.user}"

    @classmethod
    def create(cls, username, first_name, last_name, phone, email, password):
        user = User.objects.create_user(
            username=username,
            first_name=first_name,
            last_name=last_name,
            email=email,
            password=password
        )
        employee = Customer()
        employee.phone = phone
        employee.user = user
        employee.save()
        return employee


class Account(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    user = models.ForeignKey(User, default="", on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    is_loan = models.BooleanField()

    def __str__(self):
        return f'{self.pk} - {self.user} - {self.name}'

    @property
    def balance(self):
        balance = Ledger.objects.filter(account=self.pk)
        balance = balance.aggregate(models.Sum('amount'))['amount__sum'] or Decimal(0)
        return balance

    @property
    def movements(self):
        return Ledger.objects.filter(account=self.pk)

    @classmethod
    def create(cls, name, pk, is_loan):
        account = Account()
        account.id = uuid.uuid4()
        account.user = User.objects.get(pk=pk)
        account.name = name
        account.is_loan = is_loan
        account.save()
        return account


class Ledger(models.Model):
    account = models.UUIDField()
    amount = models.DecimalField(max_digits=100, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    text = models.CharField(max_length=300)
    transaction_id = models.UUIDField()
    registration_number = models.CharField(max_length=4)

    def __str__(self):
        return f'{self.account} - {self.amount} - {self.text}'

    @classmethod
    def internal_transfer(cls, amount, from_account_id, to_account_id, from_text, to_text, is_loan=False):
        transaction_id = uuid.uuid4()
        with transaction.atomic():
            from_account = Account.objects.get(pk=from_account_id)
            print(from_account)
            if from_account.balance >= amount or is_loan:
                Ledger.objects.create(amount=-amount, account=from_account_id, text=from_text, transaction_id=transaction_id, registration_number=settings.BANK_REGISTRATION_NUMBER)
                Ledger.objects.create(amount=amount, account=to_account_id, text=to_text, transaction_id=transaction_id, registration_number=settings.BANK_REGISTRATION_NUMBER)
            else:
                # Show error message to user
                raise Exception("Not enough money on account")

    @classmethod
    def external_transfer(cls, amount, from_account_id, to_account_id, from_text, to_text, to_registraton_number):
        transaction_id = uuid.uuid4()
        api = ""

        with transaction.atomic():
            from_account = Account.objects.get(pk=from_account_id)
            if from_account.balance >= amount:
                Ledger.objects.create(amount=-amount, account=from_account_id, text=from_text, transaction_id=transaction_id, registration_number=settings.BANK_REGISTRATION_NUMBER)
                Ledger.objects.create(amount=amount, account=to_account_id, text=to_text, transaction_id=transaction_id, registration_number=to_registraton_number)
            else:
                # Show error message to user
                raise Exception("Not enough money on account")

        # registration_number_for_other_bank = settings.BANKS.find something here
        for bank in settings.BANKS:
            if bank['registration_number'] == to_registraton_number:
                print(bank['api'])
                api = bank['api']

        transfer = {
            'amount': amount,
            'from_account_id': from_account_id,
            'to_account_id': to_account_id,
            'from_text': from_text,
            'to_text': to_text
        }

        response = requests.post(api, data=json.dumps(transfer))
        print(api)
        print(response.json())

        # TODO
        # To auth or not to auth?
        # Validate that other account exists
        # Only complete transfer if succeeded on other account
        # Idempotency key

        print("We do this external shit")
        pass

bank_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Account, Customer, Employee, Ledger
from django.contrib.auth import logout as dj_logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.conf import settings

# TEST MEEEEEEEE
import requests

# REST API
from rest_framework.decorators import api_view
from rest_framework.parsers import JSONParser
from django.http.response import JsonResponse


@api_view(['POST'])
def external_transfer(request):
    if request.method == 'POST':
        print("hello world")
        transfer = JSONParser().parse(request)

        amount = transfer['amount']
        from_account_id = transfer['from_account_id']
        to_account_id = transfer['to_account_id']
        from_text = transfer['from_text']
        to_text = transfer['to_text']

        Ledger.internal_transfer(amount, from_account_id, to_account_id, from_text, to_text)
        return JsonResponse("hi mom its me POST", safe=False)


def test_me(request):
    response = requests.get("http://127.0.0.1:4321/ledgers", auth=('a', 'kage1234'))
    ledgers = response.json()
    return render(request, 'bank_app/test_me.html', {'ledgers': ledgers})


def index(request):
    user_id = request.user.pk

    if request.user.is_authenticated:
        if not request.user.is_verified():
            # user not logged in using two-factor
            return HttpResponseRedirect(reverse('two_factor:setup'))

        # if user is employee, should not access /customer.html
        if Customer.objects.filter(user=user_id).exists():
            return render(request, 'bank_app/customer.html', {'customer': request.user.customer, 'bank_registration_number': settings.BANK_REGISTRATION_NUMBER})
        elif Employee.objects.filter(user=user_id).exists():
            return render(request, 'bank_app/employee.html', {})
        else:
            print(Customer.objects.all())
            print('logging out')
            logout(request)
            return HttpResponseRedirect(reverse('two_factor:login'))

    else:
        return HttpResponseRedirect(reverse('two_factor:login'))

@login_required
def customer_details(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    return render(request, 'bank_app/customer_details.html', {'customer': customer})

@login_required
def get_customers_partial(request):
    customers = Customer.objects.all()
    return render(request, 'bank_app/customers_list_partial.html', {'customers': customers})

@login_required
def create_customer(request):
    username = request.POST['username']
    first_name = request.POST['first_name']
    last_name = request.POST['last_name']
    phone = request.POST['phone']
    email = request.POST['email']
    password = request.POST['password']

    customer = Customer.create(username, first_name, last_name, phone, email, password)
    response = render(request, 'bank_app/customers_list_partial.html', {'customers': [customer]})
    return response

@login_required
def get_accounts_partial(request, pk):
    accounts = Account.objects.filter(user=pk)
    return render(request, 'bank_app/accounts_list_partial.html', {'accounts': accounts})

@login_required
def create_account(request):
    name = request.POST['name']
    pk = request.POST['pk']
    is_loan = request.POST.get('is_loan', False)
    account = Account.create(name, pk, is_loan)
    response = render(request, 'bank_app/accounts_list_partial.html', {'accounts': [account]})
    return response

@login_required
def set_rank(request):
    pk = request.POST['pk']
    rank = request.POST['rank']
    customer = get_object_or_404(Customer, pk=pk)
    customer.set_rank(rank)
    response = render(request, 'bank_app/rank_partial.html', {'rank': rank})
    return response

@login_required
def create_transfer(request):
    from_account_id = request.POST['from_account_id']
    from_text = request.POST['from_text']

    to_account_id = request.POST['to_account_id']
    to_text = request.POST['to_text']
    to_registraton_number = request.POST['to_registraton_number']

    amount = float(request.POST['amount'])
    internal_bank_registration_number = settings.BANK_REGISTRATION_NUMBER
    banks = settings.BANKS

    context = {
        'customer': request.user.customer,
    }

    if not any(bank['registration_number'] == to_registraton_number for bank in banks):
        context['message'] = {
            'text': 'Account does not exist',
            'type': 'error'
        }
        response = render(request, 'bank_app/create_transfer_partial.html', context)
    elif to_registraton_number == internal_bank_registration_number:
        Ledger.internal_transfer(amount, from_account_id, to_account_id, from_text, to_text)
        context['message'] = {
            'text': 'Your money was transfered successfully',
            'type': 'success'
        }
        response = render(request, 'bank_app/create_transfer_partial.html', context)
        response.headers["HX-Trigger"] = "accountUpdate"
    else:
        print("Other bank")
        Ledger.external_transfer(amount, from_account_id, to_account_id, from_text, to_text, to_registraton_number)
        context['message'] = {
            'text': 'Your money was transfered successfully',
            'type': 'success'
        }
        response = render(request, 'bank_app/create_transfer_partial.html', context)
        response.headers["HX-Trigger"] = "accountUpdate"

    return response

@login_required
def create_loan(request):
    amount = float(request.POST['amount'])
    name = request.POST['loan_name']
    to_account_id = request.POST['to_account_id']
    pk = request.user.pk

    # Can they make a loan?
    if request.user.customer.can_make_loan:
        # If yes - make loan
        request.user.customer.create_loan(name, pk, amount, to_account_id)
    # Else return error message
    response = render(request, 'bank_app/customer.html', {'customer': request.user.customer})
    return response

@login_required
def account_details(request, pk):
    account = get_object_or_404(Account, pk=pk)
    is_employee = Employee.objects.filter(user=request.user.pk).exists()
    is_owner_of_account = request.user.pk == account.user.pk

    if not is_owner_of_account and not is_employee:
        return HttpResponseRedirect(reverse('bank_app:index'))

    return render(request, 'bank_app/account_details.html', {'account': account})

@login_required
def get_account_movements_partial(request, pk):
    account = get_object_or_404(Account, pk=pk)
    movements = account.movements

    return render(request, 'bank_app/account_movements_partial.html', {'movements': movements})

@login_required
def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse('login'))

bank_app/templates/bank_app/account_details.html
{% extends './base.html' %} {% block content %}
<a href="javascript:history.back()">Back</a>

<h1>Account: {{account.name|title}} 
    {% if account.is_loan %}
    (Loan)
    {% endif%}
</h1>

<h2>Account movements</h2>
<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody
    id="account_movements_list"
    hx-swap="innerHTML"
    hx-get="{% url 'bank_app:get_account_movements_partial' account.pk %}"
    hx-trigger="load"
  ></tbody>
</table>

<h3>Balance: {{account.balance}}</h3>

{% endblock %}

bank_app/templates/bank_app/account_movements_partial.html
{% for movement in movements %}
<tr>
  <td>{{ movement.text }}
    <br/>
    <i style="color: grey;">{{ movement.timestamp}}</i>
  </td>
  <td {% if movement.amount > 0 %} style="color: green;" {% endif %}>
  {{ movement.amount }}</td>
</tr>
{% endfor %}

bank_app/templates/bank_app/accounts_list_partial.html
{% for account in accounts %}
<tr onclick="window.location.href='{% url "bank_app:account_details" account.pk %}'" style="cursor: pointer;">
  <td>{{ account.name }}</td>
  <td>{{ account.is_loan }}</td>
  <td>{{ account.balance }}</td>
</tr>
{% endfor %}

bank_app/templates/bank_app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://classless.de/classless-tiny.css" />
    <title>Bank</title>
  </head>
  <body>
    {% block content %} {% endblock %}
    <footer style="height: 30px;"></footer>
    <script defer src="https://unpkg.com/htmx.org@1.8.0"></script>
    <script defer>
      document.body.addEventListener("htmx:configRequest", (event) => {
        event.detail.headers["X-CSRFToken"] = "{{ csrf_token }}";
      });
    </script>
  </body>
</html>

bank_app/templates/bank_app/create_transfer_partial.html
{% if message %}<h4 style="color: {% if message.type == 'success'  %}green{% else %}red{% endif %}"> {{ message.text }} </h4>{% endif %}

bank_app/templates/bank_app/customer.html
{% extends './base.html' %} {% block content %}

<a href="{% url 'bank_app:logout' %}">Log out</a>
<h1>
    Hello {{customer.user.first_name}}!
</h1>
<p>Rank: {{customer.rank}}</p>

<h2>Accounts</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Is loan</th>
      <th>Balance</th>
    </tr>
  </thead>
  <tbody
    id="accounts_list"
    hx-swap="innerHTML"
    hx-get="{% url 'bank_app:get_accounts_partial' customer.pk %}"
    hx-trigger="load, accountUpdate from:body"
  ></tbody>
</table>

<h2>Transfer money</h2>
<form style="display: flex; flex-direction: column; align-items: flex-start; gap: 10px;">
    {% csrf_token %}
    <input name="bank_registration_number" type="hidden" value="{{ bank_registration_number }}" />
    <fieldset>
        <legend>From</legend>
        <label style="display: flex; flex-direction: column; align-items: flex-start;">
            <span>Account</span>
            <select name="from_account_id">
                <option value=""></option>
                {% for account in customer.accounts %}
                <option value="{{account.pk}}">{{account.name}}</option>
                {% endfor %}
            </select>
        </label>
        <label style="display: flex; flex-direction: column; align-items: flex-start;">
            <span>Text on account statement</span>
            <input name="from_text" type="text" />
        </label>
        <label style="display: flex; flex-direction: column; align-items: flex-start;">
            <span>Amount</span>
            <input name="amount" type="number" placeholder="Enter amount" />
        </label>
    </fieldset>
    <fieldset>
        <legend>To</legend>
        <div style="display: flex; gap: 10px;">
            <label style="display: flex; flex-direction: column; align-items: flex-start;">
                <span>Account</span>
                <select class="accounts" name="accounts">
                    <option value=""></option>
                    {% for account in customer.accounts %}
                    <option value="{{account.pk}}">{{account.name}}</option>
                    {% endfor %}
                </select>
            </label>
            <p>Or</p>
            <label style="display: flex; flex-direction: column; align-items: flex-start;">
                <span>Account number</span>
                <input class="to_account_id" name="to_account_id" type="text" placeholder="Enter account number"/>
            </label>
            <label style="display: flex; flex-direction: column; align-items: flex-start;">
                <span>Registration number</span>
                <input class="to_registraton_number" name="to_registraton_number" type="text" placeholder="Enter registration number"/>
            </label>
        </div>
        <label style="display: flex; flex-direction: column; align-items: flex-start;">
            <span>Text on receiver statement</span>
            <input name="to_text" type="text"/>
        </label>
    </fieldset>
    <button
        hx-post="{% url 'bank_app:create_transfer' %}"
        hx-trigger="click"
        hx-swap="innerHTML"
        hx-target="#message"
    >Transfer</button>
    <div id="message"></div>
</form>

{% if customer.can_make_loan %}
    <h2>Make a loan</h2>
    <form action="{% url 'bank_app:create_loan' %}" method="post">
        {% csrf_token %}
        <input name="bank_registration_number" type="hidden" value="{{ bank_registration_number }}" />
        <fieldset>
            <label style="display: flex; flex-direction: column; align-items: flex-start;">
                <span>Amount</span>
                <input name="amount" type="number" placeholder="Enter amount"/>
            </label>
            <label style="display: flex; flex-direction: column; align-items: flex-start;">
                <span>Name on loan</span>
                <input name="loan_name" type="text"/>
            </label>
            <div style="display: flex; gap: 10px;">
                <label style="display: flex; flex-direction: column; align-items: flex-start;">
                    <span>To account</span>
                    <select class="accounts" name="accounts">
                        <option value=""></option>
                        {% for account in customer.accounts %}
                            {% if not account.is_loan %}
                                <option value="{{account.pk}}">{{account.name}}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </label>
                <p>Or</p>
                <label style="display: flex; flex-direction: column; align-items: flex-start;">
                    <span>To account number</span>
                    <input class="to_account_id" name="to_account_id" type="text" placeholder="Enter account number"/>
                </label>
                <label style="display: flex; flex-direction: column; align-items: flex-start;">
                    <span>Registration number</span>
                    <input class="to_registraton_number" name="to_registraton_number" type="text" placeholder="Enter registration number"/>
                </label>
            </div>
            
        </fieldset>
        <button>Create loan</button>
    </form>
{% endif %}


<script defer>
    const select = document.querySelectorAll(".accounts");

    select.forEach(select => {
        const form = select.closest("form");
        
        select.addEventListener("change", (e) => {
            console.log("pandekage")
            const accountNumberInput = form.querySelector(".to_account_id");
            const regNumberInput = form.querySelector(".to_registraton_number");
            const bankRegNumber = form.querySelector('input[name="bank_registration_number"]');
            
            regNumberInput.value = bankRegNumber.value;
            accountNumberInput.value = e.target.value;
        });
    });
</script>

{% endblock %}

bank_app/templates/bank_app/customer_details.html
{% extends './base.html' %} {% block content %}

<a href="{% url 'bank_app:employee' %}">Back</a>
<h1>Customer details for {{ customer.user.username }}</h1>
<ul>
  <li>User name: {{ customer.user.username }}</li>
  <li>Phone number: {{ customer.phone }}</li>
  <li>Email: {{ customer.user.email }}</li>
  <li>Rank: <span id="rank_display">{{ customer.rank }}</span></li>
</ul>

<form
  style="
    display: flex;
    gap: 1rem;
    flex-direction: column;
    align-items: flex-start;
  "
>
  <h2>Change rank</h2>
  <input name="pk" type="hidden" value="{{ customer.pk }}" />
  <label for="rank">Rank:</label>
  <select id="rank" name="rank">
    <option value="Basic">Basic</option>
    <option value="Silver">Silver</option>
    <option value="Gold">Gold</option>
  </select>
  <button
    hx-post="{% url 'bank_app:set_rank' %}"
    hx-trigger="click"
    hx-swap="innerHTML"
    hx-target="#rank_display"
  >
    Change rank
  </button>
</form>

<form
  style="
    display: flex;
    gap: 1rem;
    flex-direction: column;
    align-items: flex-start;
  "
>
  <h2>Create account</h2>
  <input placeholder="Name" name="name" />
  <input name="pk" type="hidden" value="{{ customer.pk }}" />
  <label for="is_loan">
    Is loan?
    <input name="is_loan" type="checkbox" />
  </label>
  <button
    hx-post="{% url 'bank_app:create_account' %}"
    hx-trigger="click"
    hx-swap="beforeend"
    hx-target="#accounts_list"
  >
    Create
  </button>
</form>

<h2>Accounts</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Is loan</th>
      <th>Balance</th>
    </tr>
  </thead>
  <tbody
    id="accounts_list"
    hx-swap="innerHTML"
    hx-get="{% url 'bank_app:get_accounts_partial' customer.pk %}"
    hx-trigger="load"
  ></tbody>
</table>
{% endblock %}

bank_app/templates/bank_app/customers_list_partial.html
{% for customer in customers %}
<tr onclick="window.location.href='{% url "bank_app:customer_details" customer.pk %}'" style="cursor: pointer;">
        <td>{{customer.pk}}</td>
        <td>{{customer.user.username}}</td>
        <td>{{customer.user.first_name}}</td>
        <td>{{customer.user.last_name}}</td>
        <td>{{customer.user.email}}</td>
        <td>{{customer.phone}}</td>
        <td>{{customer.rank}}</td>
</tr>
{% endfor %}

bank_app/templates/bank_app/employee.html
{% extends './base.html' %} {% block content %}
<h1>Hello, you are an employee!</h1>
<p>hope you get paid well</p>
<a href="{% url 'bank_app:logout' %}">Log out</a>

<form style="
        display: flex;
        gap: 1rem;
        flex-direction: column;
        align-items: flex-start;
      ">
  <h2>Create customer</h2>
  <input placeholder="Username" name="username" />
  <input placeholder="First name" name="first_name" />
  <input placeholder="Last name" name="last_name" />
  <input placeholder="Email" name="email" />
  <input placeholder="Phone number" name="phone" />
  <input placeholder="Password" name="password" type="password" />
  <button
    hx-post="{% url 'bank_app:create_customer' %}"
    hx-trigger="click"
    hx-swap="beforeend"
    hx-target="#customer_list"
  >
    Create
  </button>
</form>
<h2>Customers</h2>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Username</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Rank</th>
    </tr>
  </thead>
  <tbody
    id="customer_list"
    hx-swap="innerHTML"
    hx-get="{% url 'bank_app:get_customers_partial' %}"
    hx-trigger="load"
  ></tbody>
</table>

{% endblock %}

bank_app/templates/bank_app/rank_partial.html
{{ rank }}

bank_app/templates/bank_app/test_me.html
<h1>Shit works</h1>